const std = @import("std");

const Compile = std.Build.Step.Compile;

const CodeUnitWidth = enum {
    @"8",
    @"16",
    @"32",
};

fn buildPcre2(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode) !*Compile {
    const codeUnitWidth: CodeUnitWidth = .@"8";
    const pcre2_header_dir = b.addWriteFiles();
    const pcre2_header = pcre2_header_dir.addCopyFile(b.path("vendor/pcre2/src/pcre2.h.generic"), "pcre2.h");

    const config_header = b.addConfigHeader(
        .{
            .style = .{ .cmake = b.path("vendor/pcre2/src/config-cmake.h.in") },
            .include_path = "config.h",
        },
        .{
            .HAVE_ASSERT_H = true,
            .HAVE_UNISTD_H = (target.result.os.tag != .windows),
            .HAVE_WINDOWS_H = (target.result.os.tag == .windows),

            .HAVE_MEMMOVE = true,
            .HAVE_STRERROR = true,

            .SUPPORT_PCRE2_8 = codeUnitWidth == CodeUnitWidth.@"8",
            .SUPPORT_PCRE2_16 = codeUnitWidth == CodeUnitWidth.@"16",
            .SUPPORT_PCRE2_32 = codeUnitWidth == CodeUnitWidth.@"32",
            .SUPPORT_UNICODE = true,

            .PCRE2_EXPORT = null,
            .PCRE2_LINK_SIZE = 2,
            .PCRE2_HEAP_LIMIT = 20000000,
            .PCRE2_MATCH_LIMIT = 10000000,
            .PCRE2_MATCH_LIMIT_DEPTH = "MATCH_LIMIT",
            .PCRE2_MAX_VARLOOKBEHIND = 255,
            .NEWLINE_DEFAULT = 2,
            .PCRE2_PARENS_NEST_LIMIT = 250,
            .PCRE2GREP_BUFSIZE = 20480,
            .PCRE2GREP_MAX_BUFSIZE = 1048576,
        },
    );

    // pcre2-8/16/32.lib

    const lib_mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });

    lib_mod.addCMacro("HAVE_CONFIG_H", "");
    lib_mod.addCMacro("PCRE2_CODE_UNIT_WIDTH", @tagName(codeUnitWidth));
    lib_mod.addCMacro("PCRE2_STATIC", "");

    const lib = b.addLibrary(.{
        .name = b.fmt("pcre2-{s}", .{@tagName(codeUnitWidth)}),
        .root_module = lib_mod,
        .linkage = .static,
    });

    lib.addConfigHeader(config_header);
    lib.addIncludePath(pcre2_header_dir.getDirectory());
    lib.addIncludePath(b.path("vendor/pcre2/src"));

    lib.addCSourceFile(.{
        .file = b.addWriteFiles().addCopyFile(b.path("vendor/pcre2/src/pcre2_chartables.c.dist"), "pcre2_chartables.c"),
    });

    lib.addCSourceFiles(.{
        .files = &.{
            "vendor/pcre2/src/pcre2_auto_possess.c",
            "vendor/pcre2/src/pcre2_chkdint.c",
            "vendor/pcre2/src/pcre2_compile.c",
            "vendor/pcre2/src/pcre2_compile_cgroup.c",
            "vendor/pcre2/src/pcre2_compile_class.c",
            "vendor/pcre2/src/pcre2_config.c",
            "vendor/pcre2/src/pcre2_context.c",
            "vendor/pcre2/src/pcre2_convert.c",
            "vendor/pcre2/src/pcre2_dfa_match.c",
            "vendor/pcre2/src/pcre2_error.c",
            "vendor/pcre2/src/pcre2_extuni.c",
            "vendor/pcre2/src/pcre2_find_bracket.c",
            "vendor/pcre2/src/pcre2_jit_compile.c",
            "vendor/pcre2/src/pcre2_maketables.c",
            "vendor/pcre2/src/pcre2_match.c",
            "vendor/pcre2/src/pcre2_match_data.c",
            "vendor/pcre2/src/pcre2_match_next.c",
            "vendor/pcre2/src/pcre2_newline.c",
            "vendor/pcre2/src/pcre2_ord2utf.c",
            "vendor/pcre2/src/pcre2_pattern_info.c",
            "vendor/pcre2/src/pcre2_script_run.c",
            "vendor/pcre2/src/pcre2_serialize.c",
            "vendor/pcre2/src/pcre2_string_utils.c",
            "vendor/pcre2/src/pcre2_study.c",
            "vendor/pcre2/src/pcre2_substitute.c",
            "vendor/pcre2/src/pcre2_substring.c",
            "vendor/pcre2/src/pcre2_tables.c",
            "vendor/pcre2/src/pcre2_ucd.c",
            "vendor/pcre2/src/pcre2_valid_utf.c",
            "vendor/pcre2/src/pcre2_xclass.c",
        },
    });

    lib.installHeader(pcre2_header, "pcre2.h");

    return lib;
}

fn buildZlib(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode) !*Compile {
    const lib_mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });

    lib_mod.addCMacro("HAVE_HIDDEN", "");
    lib_mod.addCMacro("_LARGEFILE64_SOURCE", "1");

    const lib = b.addLibrary(.{
        .name = b.fmt("libz", .{}),
        .root_module = lib_mod,
        .linkage = .static,
    });

    lib.addIncludePath(b.path("vendor/zlib"));

    lib.addCSourceFiles(.{
        .files = &.{
            "vendor/zlib/crc32.c",
            "vendor/zlib/adler32.c",
            "vendor/zlib/infback.c",
            "vendor/zlib/inffast.c",
            "vendor/zlib/inflate.c",
            "vendor/zlib/trees.c",
            "vendor/zlib/deflate.c",
            "vendor/zlib/inftrees.c",
            "vendor/zlib/zutil.c",
            "vendor/zlib/compress.c",
            "vendor/zlib/uncompr.c",
            "vendor/zlib/gzclose.c",
            "vendor/zlib/gzlib.c",
            "vendor/zlib/gzread.c",
            "vendor/zlib/gzwrite.c",
        },
    });

    return lib;
}

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // Build openssl
    const crypto = libcrypto(b, target, optimize);
    const ssl = libssl(b, target, optimize);

    crypto.installHeadersDirectory(b.path("vendor/openssl-zig/include/crypto"), "crypto", .{});
    crypto.installHeadersDirectory(b.path("vendor/openssl-zig/include/internal"), "internal", .{});
    ssl.installHeadersDirectory(b.path("vendor/openssl-zig/include/openssl"), "openssl", .{});
    ssl.installHeadersDirectory(b.path("vendor/openssl-zig/include_gen"), "", .{});

    b.installArtifact(crypto);
    b.installArtifact(ssl);
    // End build openssl

    const pcre2 = try buildPcre2(b, target, optimize);
    const zlib = try buildZlib(b, target, optimize);

    const nginx_mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
    });

    const flags = [_][]const u8{ "-std=gnu11", "-DZIG_BUILD", "-D_GNU_SOURCE" };

    const nginx_sources_common = [_][]const u8{
        "src/core/nginx.c",
        "src/core/ngx_array.c",
        "src/core/ngx_buf.c",
        "src/core/ngx_conf_file.c",
        "src/core/ngx_connection.c",
        "src/core/ngx_cpuinfo.c",
        "src/core/ngx_crc32.c",
        "src/core/ngx_crypt.c",
        "src/core/ngx_cycle.c",
        "src/core/ngx_file.c",
        "src/core/ngx_hash.c",
        "src/core/ngx_inet.c",
        "src/core/ngx_list.c",
        "src/core/ngx_log.c",
        "src/core/ngx_md5.c",
        "src/core/ngx_module.c",
        "src/core/ngx_murmurhash.c",
        "src/core/ngx_open_file_cache.c",
        "src/core/ngx_output_chain.c",
        "src/core/ngx_palloc.c",
        "src/core/ngx_parse_time.c",
        "src/core/ngx_parse.c",
        "src/core/ngx_proxy_protocol.c",
        "src/core/ngx_queue.c",
        "src/core/ngx_radix_tree.c",
        "src/core/ngx_rbtree.c",
        "src/core/ngx_regex.c",
        "src/core/ngx_resolver.c",
        "src/core/ngx_rwlock.c",
        "src/core/ngx_sha1.c",
        "src/core/ngx_shmtx.c",
        "src/core/ngx_slab.c",
        "src/core/ngx_spinlock.c",
        "src/core/ngx_string.c",
        "src/core/ngx_syslog.c",
        "src/core/ngx_times.c",
        "src/event/modules/ngx_iocp_module.c",
        "src/event/modules/ngx_win32_poll_module.c",
        "src/event/modules/ngx_win32_select_module.c",
        "src/event/ngx_event_accept.c",
        "src/event/ngx_event_acceptex.c",
        "src/event/ngx_event_connect.c",
        "src/event/ngx_event_openssl.c",
        "src/event/ngx_event_openssl_cache.c",
        "src/event/ngx_event_openssl_stapling.c",
        "src/event/ngx_event_pipe.c",
        "src/event/ngx_event_posted.c",
        "src/event/ngx_event_timer.c",
        "src/event/ngx_event_udp.c",
        "src/event/ngx_event.c",
        "src/http/modules/ngx_http_access_module.c",
        "src/http/modules/ngx_http_auth_basic_module.c",
        "src/http/modules/ngx_http_autoindex_module.c",
        "src/http/modules/ngx_http_browser_module.c",
        "src/http/modules/ngx_http_charset_filter_module.c",
        "src/http/modules/ngx_http_chunked_filter_module.c",
        "src/http/modules/ngx_http_empty_gif_module.c",
        "src/http/modules/ngx_http_fastcgi_module.c",
        "src/http/modules/ngx_http_geo_module.c",
        "src/http/modules/ngx_http_gzip_filter_module.c",
        "src/http/modules/ngx_http_headers_filter_module.c",
        "src/http/modules/ngx_http_index_module.c",
        "src/http/modules/ngx_http_limit_conn_module.c",
        "src/http/modules/ngx_http_limit_req_module.c",
        "src/http/modules/ngx_http_log_module.c",
        "src/http/modules/ngx_http_map_module.c",
        "src/http/modules/ngx_http_memcached_module.c",
        "src/http/modules/ngx_http_mirror_module.c",
        "src/http/modules/ngx_http_not_modified_filter_module.c",
        "src/http/modules/ngx_http_proxy_module.c",
        "src/http/modules/ngx_http_range_filter_module.c",
        "src/http/modules/ngx_http_rewrite_module.c",
        "src/http/modules/ngx_http_referer_module.c",
        "src/http/modules/ngx_http_scgi_module.c",
        "src/http/modules/ngx_http_split_clients_module.c",
        "src/http/modules/ngx_http_ssi_filter_module.c",
        "src/http/modules/ngx_http_static_module.c",
        "src/http/modules/ngx_http_try_files_module.c",
        "src/http/modules/ngx_http_upstream_hash_module.c",
        "src/http/modules/ngx_http_upstream_ip_hash_module.c",
        "src/http/modules/ngx_http_upstream_keepalive_module.c",
        "src/http/modules/ngx_http_upstream_least_conn_module.c",
        "src/http/modules/ngx_http_upstream_random_module.c",
        "src/http/modules/ngx_http_upstream_zone_module.c",
        "src/http/modules/ngx_http_userid_filter_module.c",
        "src/http/modules/ngx_http_uwsgi_module.c",
        "src/http/ngx_http_copy_filter_module.c",
        "src/http/ngx_http_core_module.c",
        "src/http/ngx_http_file_cache.c",
        "src/http/ngx_http_header_filter_module.c",
        "src/http/ngx_http_parse.c",
        "src/http/ngx_http_postpone_filter_module.c",
        "src/http/ngx_http_request_body.c",
        "src/http/ngx_http_request.c",
        "src/http/ngx_http_script.c",
        "src/http/ngx_http_special_response.c",
        "src/http/ngx_http_upstream_round_robin.c",
        "src/http/ngx_http_upstream.c",
        "src/http/ngx_http_variables.c",
        "src/http/ngx_http_write_filter_module.c",
        "src/http/ngx_http.c",
    };

    const nginx_sources_win32 = [_][]const u8{
        "src/os/win32/ngx_alloc.c",
        "src/os/win32/ngx_dlopen.c",
        "src/os/win32/ngx_errno.c",
        "src/os/win32/ngx_event_log.c",
        "src/os/win32/ngx_files.c",
        "src/os/win32/ngx_process_cycle.c",
        "src/os/win32/ngx_process.c",
        "src/os/win32/ngx_shmem.c",
        "src/os/win32/ngx_socket.c",
        "src/os/win32/ngx_thread.c",
        "src/os/win32/ngx_time.c",
        "src/os/win32/ngx_udp_wsarecv.c",
        "src/os/win32/ngx_user.c",
        "src/os/win32/ngx_win32_init.c",
        "src/os/win32/ngx_wsarecv_chain.c",
        "src/os/win32/ngx_wsarecv.c",
        "src/os/win32/ngx_wsasend_chain.c",
        "src/os/win32/ngx_wsasend.c",
        "zig/win32/ngx_modules.c",
    };

    const sources = try std.mem.concat(std.heap.page_allocator, []const u8, &.{ &nginx_sources_common, &nginx_sources_win32 });

    nginx_mod.addCSourceFiles(.{
        .files = sources,
        .flags = &flags,
    });

    nginx_mod.addIncludePath(b.path("src/core"));
    nginx_mod.addIncludePath(b.path("src/http"));
    nginx_mod.addIncludePath(b.path("src/http/modules"));
    nginx_mod.addIncludePath(b.path("src/event"));
    nginx_mod.addIncludePath(b.path("src/event/modules"));
    nginx_mod.addIncludePath(b.path("zig/win32"));
    nginx_mod.addIncludePath(b.path("src/os/win32"));
    nginx_mod.addIncludePath(b.path("vendor/pcre2/src"));
    nginx_mod.addIncludePath(b.path("vendor/zlib"));

    // This is bad
    nginx_mod.addIncludePath(b.path("zig-out/include"));

    // ssl.installHeadersDirectory(b.path("vendor/openssl-zig/include/openssl"), "openssl", .{});
    // b.getInstallPath(dir: InstallDir, dest_rel_path: []const u8)
    // const sslHeaders = ssl.installed_headers;
    // for (sslHeaders.items) |installation| {
    //     // header.directory
    //     switch (installation) {
    //         .file => |f| nginx_mod.addConfigHeader(f),
    //         .directory => |d| {
    //             nginx_mod.addIncludePath(d);
    //         },
    //     }
    // }

    // nginx_mod.addCMacro("OPENSSL_API_COMPAT", "30500");
    // nginx_mod.addCMacro("OPENSSL_NO_DEPRECATED", "");
    nginx_mod.addCMacro("FD_SETSIZE", "1024");
    nginx_mod.addCMacro("PCRE2_STATIC", "");
    nginx_mod.addCMacro("HAVE_HIDDEN", "");
    nginx_mod.addCMacro("_LARGEFILE64_SOURCE", "1");

    const exe = b.addExecutable(.{
        .linkage = .dynamic,
        .name = "nginx",
        .root_module = nginx_mod,
    });

    exe.step.dependOn(&pcre2.step);
    exe.step.dependOn(&zlib.step);
    exe.step.dependOn(&crypto.step);
    exe.step.dependOn(&ssl.step);

    exe.linkLibC();
    exe.linkSystemLibrary("ws2_32");
    exe.linkLibrary(pcre2);
    exe.linkLibrary(zlib);
    exe.linkLibrary(crypto);
    exe.linkLibrary(ssl);

    b.installArtifact(pcre2);
    b.installArtifact(zlib);
    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);

    run_cmd.step.dependOn(b.getInstallStep());

    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}

fn libcrypto(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode) *std.Build.Step.Compile {
    const lib = b.addStaticLibrary(.{
        .name = "crypto",
        .target = target,
        .optimize = optimize,
    });
    lib.pie = true;
    switch (optimize) {
        .Debug, .ReleaseSafe => lib.bundle_compiler_rt = true,
        else => lib.root_module.strip = true,
    }
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/include"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/providers/common/include"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/providers/fips"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/providers/implementations/include"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/include_gen"));
    // lib.root_module.addCMacro("OPENSSL_NO_DEPRECATED", "");
    lib.root_module.addCMacro("OPENSSL_NO_ENGINE", "");
    lib.root_module.addCMacro("OPENSSL_NO_SRP", "");
    lib.root_module.addCMacro("OPENSSL_NO_UI_CONSOLE", "");
    lib.root_module.addCMacro("OPENSSL_NO_ASAN", "");
    lib.root_module.addCMacro("OPENSSL_NO_UBSAN", "");
    lib.root_module.addCMacro("OPENSSL_NO_ASM", "");
    lib.root_module.addCMacro("OPENSSL_NO_KTLS", "");
    lib.root_module.addCMacro("OPENSSL_NO_QUIC", "");
    lib.root_module.addCMacro("OPENSSL_NO_THREAD_POOL", "");
    // lib.root_module.addCMacro("OPENSSL_NO_STDIO", "");
    lib.root_module.addCMacro("OPENSSL_NO_JITTER", "");
    lib.root_module.addCMacro("OPENSSLDIR", "\"/usr/local/ssl\"");
    lib.root_module.addCMacro("OSSL_PKEY_PARAM_RSA_DERIVE_FROM_PQ", "1");
    if (lib.rootModuleTarget().isMinGW())
        lib.root_module.addCMacro("NOCRYPT", "1");
    if (lib.rootModuleTarget().os.tag.isDarwin())
        // CommonCrypto
        lib.root_module.linkFramework("CoreServices", .{});
    if (lib.rootModuleTarget().cpu.arch.isRISCV())
        lib.root_module.addCMacro("__NR_riscv_hwprobe", "(__NR_arch_specific_syscall + 14)");
    lib.root_module.addCSourceFiles(.{
        .files = switch (lib.rootModuleTarget().cpu.arch) {
            .arm, .aarch64 => &.{
                "vendor/openssl-zig/crypto/armcap.c",
            },
            .powerpc => &.{
                "vendor/openssl-zig/crypto/ppccap.c",
            },
            .riscv64 => &.{
                "vendor/openssl-zig/crypto/riscvcap.c",
            },
            .s390x => &.{
                "vendor/openssl-zig/crypto/bn/bn_s390x.c",
                "vendor/openssl-zig/crypto/ec/ecp_s390x_nistp.c",
                "vendor/openssl-zig/crypto/ec/ecx_s390x.c",
                "vendor/openssl-zig/crypto/s390xcap.c",
            },
            .sparc, .sparc64 => &.{
                "vendor/openssl-zig/crypto/bn/bn_sparc.c",
                "vendor/openssl-zig/crypto/sparcv9cap.c",
            },
            else => &.{
                "vendor/openssl-zig/crypto/cpuid.c",
            },
        },
        .flags = &.{
            "-std=gnu99",
            "-Wno-unknown-warning-option",
            "-Wswitch-default",
            "-Wno-parentheses-equality",
            "-Wno-language-extension-token",
            "-Wno-extended-offsetof",
            "-Wconditional-uninitialized",
            "-Wincompatible-pointer-types-discards-qualifiers",
            "-Wmissing-variable-declarations",
            "-Wno-int-conversion",
        },
    });
    lib.root_module.addCSourceFiles(.{
        .files = &.{
            // "crypto/LPdir_nyi.c",
            // "crypto/LPdir_unix.c",
            // "crypto/LPdir_vms.c",
            // "crypto/LPdir_win.c",
            // "crypto/LPdir_win32.c",
            // "crypto/LPdir_wince.c",
            "vendor/openssl-zig/crypto/aes/aes_cbc.c",
            "vendor/openssl-zig/crypto/aes/aes_cfb.c",
            "vendor/openssl-zig/crypto/aes/aes_core.c",
            "vendor/openssl-zig/crypto/aes/aes_ecb.c",
            "vendor/openssl-zig/crypto/aes/aes_ige.c",
            "vendor/openssl-zig/crypto/aes/aes_misc.c",
            "vendor/openssl-zig/crypto/aes/aes_ofb.c",
            "vendor/openssl-zig/crypto/aes/aes_wrap.c",
            "vendor/openssl-zig/crypto/aes/aes_x86core.c",
            "vendor/openssl-zig/crypto/aria/aria.c",
            "vendor/openssl-zig/crypto/asn1/a_bitstr.c",
            "vendor/openssl-zig/crypto/asn1/a_d2i_fp.c",
            "vendor/openssl-zig/crypto/asn1/a_digest.c",
            "vendor/openssl-zig/crypto/asn1/a_dup.c",
            "vendor/openssl-zig/crypto/asn1/a_gentm.c",
            "vendor/openssl-zig/crypto/asn1/a_i2d_fp.c",
            "vendor/openssl-zig/crypto/asn1/a_int.c",
            "vendor/openssl-zig/crypto/asn1/a_mbstr.c",
            "vendor/openssl-zig/crypto/asn1/a_object.c",
            "vendor/openssl-zig/crypto/asn1/a_octet.c",
            "vendor/openssl-zig/crypto/asn1/a_print.c",
            "vendor/openssl-zig/crypto/asn1/a_sign.c",
            "vendor/openssl-zig/crypto/asn1/a_strex.c",
            "vendor/openssl-zig/crypto/asn1/a_strnid.c",
            "vendor/openssl-zig/crypto/asn1/a_time.c",
            "vendor/openssl-zig/crypto/asn1/a_type.c",
            "vendor/openssl-zig/crypto/asn1/a_utctm.c",
            "vendor/openssl-zig/crypto/asn1/a_utf8.c",
            "vendor/openssl-zig/crypto/asn1/a_verify.c",
            "vendor/openssl-zig/crypto/asn1/ameth_lib.c",
            "vendor/openssl-zig/crypto/asn1/asn1_err.c",
            "vendor/openssl-zig/crypto/asn1/asn1_gen.c",
            "vendor/openssl-zig/crypto/asn1/asn1_item_list.c",
            "vendor/openssl-zig/crypto/asn1/asn1_lib.c",
            "vendor/openssl-zig/crypto/asn1/asn1_parse.c",
            "vendor/openssl-zig/crypto/asn1/asn_mime.c",
            "vendor/openssl-zig/crypto/asn1/asn_moid.c",
            "vendor/openssl-zig/crypto/asn1/asn_mstbl.c",
            "vendor/openssl-zig/crypto/asn1/asn_pack.c",
            "vendor/openssl-zig/crypto/asn1/bio_asn1.c",
            "vendor/openssl-zig/crypto/asn1/bio_ndef.c",
            "vendor/openssl-zig/crypto/asn1/d2i_param.c",
            "vendor/openssl-zig/crypto/asn1/d2i_pr.c",
            "vendor/openssl-zig/crypto/asn1/d2i_pu.c",
            "vendor/openssl-zig/crypto/asn1/evp_asn1.c",
            "vendor/openssl-zig/crypto/asn1/f_int.c",
            "vendor/openssl-zig/crypto/asn1/f_string.c",
            "vendor/openssl-zig/crypto/asn1/i2d_evp.c",
            "vendor/openssl-zig/crypto/asn1/n_pkey.c",
            "vendor/openssl-zig/crypto/asn1/nsseq.c",
            "vendor/openssl-zig/crypto/asn1/p5_pbe.c",
            "vendor/openssl-zig/crypto/asn1/p5_pbev2.c",
            "vendor/openssl-zig/crypto/asn1/p5_scrypt.c",
            "vendor/openssl-zig/crypto/asn1/p8_pkey.c",
            "vendor/openssl-zig/crypto/asn1/t_bitst.c",
            "vendor/openssl-zig/crypto/asn1/t_pkey.c",
            "vendor/openssl-zig/crypto/asn1/t_spki.c",
            "vendor/openssl-zig/crypto/asn1/tasn_dec.c",
            "vendor/openssl-zig/crypto/asn1/tasn_enc.c",
            "vendor/openssl-zig/crypto/asn1/tasn_fre.c",
            "vendor/openssl-zig/crypto/asn1/tasn_new.c",
            "vendor/openssl-zig/crypto/asn1/tasn_prn.c",
            "vendor/openssl-zig/crypto/asn1/tasn_scn.c",
            "vendor/openssl-zig/crypto/asn1/tasn_typ.c",
            "vendor/openssl-zig/crypto/asn1/tasn_utl.c",
            "vendor/openssl-zig/crypto/asn1/x_algor.c",
            "vendor/openssl-zig/crypto/asn1/x_bignum.c",
            "vendor/openssl-zig/crypto/asn1/x_info.c",
            "vendor/openssl-zig/crypto/asn1/x_int64.c",
            "vendor/openssl-zig/crypto/asn1/x_long.c",
            "vendor/openssl-zig/crypto/asn1/x_pkey.c",
            "vendor/openssl-zig/crypto/asn1/x_sig.c",
            "vendor/openssl-zig/crypto/asn1/x_spki.c",
            "vendor/openssl-zig/crypto/asn1/x_val.c",
            "vendor/openssl-zig/crypto/asn1_dsa.c",
            "vendor/openssl-zig/crypto/async/arch/async_null.c",
            if (lib.rootModuleTarget().os.tag == .windows)
                "vendor/openssl-zig/crypto/async/arch/async_win.c"
            else
                "vendor/openssl-zig/crypto/async/arch/async_posix.c",
            "vendor/openssl-zig/crypto/async/async.c",
            "vendor/openssl-zig/crypto/async/async_err.c",
            "vendor/openssl-zig/crypto/async/async_wait.c",
            "vendor/openssl-zig/crypto/bf/bf_cfb64.c",
            "vendor/openssl-zig/crypto/bf/bf_ecb.c",
            "vendor/openssl-zig/crypto/bf/bf_enc.c",
            "vendor/openssl-zig/crypto/bf/bf_ofb64.c",
            "vendor/openssl-zig/crypto/bf/bf_skey.c",
            "vendor/openssl-zig/crypto/bio/bf_buff.c",
            "vendor/openssl-zig/crypto/bio/bf_lbuf.c",
            "vendor/openssl-zig/crypto/bio/bf_nbio.c",
            "vendor/openssl-zig/crypto/bio/bf_null.c",
            "vendor/openssl-zig/crypto/bio/bf_prefix.c",
            "vendor/openssl-zig/crypto/bio/bf_readbuff.c",
            "vendor/openssl-zig/crypto/bio/bio_addr.c",
            "vendor/openssl-zig/crypto/bio/bio_cb.c",
            "vendor/openssl-zig/crypto/bio/bio_dump.c",
            "vendor/openssl-zig/crypto/bio/bio_err.c",
            "vendor/openssl-zig/crypto/bio/bio_lib.c",
            "vendor/openssl-zig/crypto/bio/bio_meth.c",
            "vendor/openssl-zig/crypto/bio/bio_print.c",
            "vendor/openssl-zig/crypto/bio/bio_sock.c",
            "vendor/openssl-zig/crypto/bio/bio_sock2.c",
            "vendor/openssl-zig/crypto/bio/bss_acpt.c",
            "vendor/openssl-zig/crypto/bio/bss_bio.c",
            "vendor/openssl-zig/crypto/bio/bss_conn.c",
            "vendor/openssl-zig/crypto/bio/bss_core.c",
            "vendor/openssl-zig/crypto/bio/bss_dgram.c",
            "vendor/openssl-zig/crypto/bio/bss_dgram_pair.c",
            "vendor/openssl-zig/crypto/bio/bss_fd.c",
            "vendor/openssl-zig/crypto/bio/bss_file.c",
            "vendor/openssl-zig/crypto/bio/bss_log.c",
            "vendor/openssl-zig/crypto/bio/bss_mem.c",
            "vendor/openssl-zig/crypto/bio/bss_null.c",
            "vendor/openssl-zig/crypto/bio/bss_sock.c",
            "vendor/openssl-zig/crypto/bio/ossl_core_bio.c",
            // "crypto/bn/asm/x86_64-gcc.c",
            "vendor/openssl-zig/crypto/bn/bn_add.c",
            "vendor/openssl-zig/crypto/bn/bn_asm.c",
            "vendor/openssl-zig/crypto/bn/bn_blind.c",
            "vendor/openssl-zig/crypto/bn/bn_const.c",
            "vendor/openssl-zig/crypto/bn/bn_conv.c",
            "vendor/openssl-zig/crypto/bn/bn_ctx.c",
            "vendor/openssl-zig/crypto/bn/bn_depr.c",
            "vendor/openssl-zig/crypto/bn/bn_dh.c",
            "vendor/openssl-zig/crypto/bn/bn_div.c",
            "vendor/openssl-zig/crypto/bn/bn_err.c",
            "vendor/openssl-zig/crypto/bn/bn_exp.c",
            "vendor/openssl-zig/crypto/bn/bn_exp2.c",
            "vendor/openssl-zig/crypto/bn/bn_gcd.c",
            "vendor/openssl-zig/crypto/bn/bn_gf2m.c",
            "vendor/openssl-zig/crypto/bn/bn_intern.c",
            "vendor/openssl-zig/crypto/bn/bn_kron.c",
            "vendor/openssl-zig/crypto/bn/bn_lib.c",
            "vendor/openssl-zig/crypto/bn/bn_mod.c",
            "vendor/openssl-zig/crypto/bn/bn_mont.c",
            "vendor/openssl-zig/crypto/bn/bn_mpi.c",
            "vendor/openssl-zig/crypto/bn/bn_mul.c",
            "vendor/openssl-zig/crypto/bn/bn_nist.c",
            "vendor/openssl-zig/crypto/bn/bn_ppc.c",
            "vendor/openssl-zig/crypto/bn/bn_prime.c",
            "vendor/openssl-zig/crypto/bn/bn_print.c",
            "vendor/openssl-zig/crypto/bn/bn_rand.c",
            "vendor/openssl-zig/crypto/bn/bn_recp.c",
            "vendor/openssl-zig/crypto/bn/bn_rsa_fips186_4.c",
            "vendor/openssl-zig/crypto/bn/bn_shift.c",
            "vendor/openssl-zig/crypto/bn/bn_sqr.c",
            "vendor/openssl-zig/crypto/bn/bn_sqrt.c",
            "vendor/openssl-zig/crypto/bn/bn_srp.c",
            "vendor/openssl-zig/crypto/bn/bn_word.c",
            "vendor/openssl-zig/crypto/bn/bn_x931p.c",
            "vendor/openssl-zig/crypto/bn/rsaz_exp.c",
            "vendor/openssl-zig/crypto/bn/rsaz_exp_x2.c",
            "vendor/openssl-zig/crypto/bsearch.c",
            "vendor/openssl-zig/crypto/buffer/buf_err.c",
            "vendor/openssl-zig/crypto/buffer/buffer.c",
            "vendor/openssl-zig/crypto/camellia/camellia.c",
            "vendor/openssl-zig/crypto/camellia/cmll_cbc.c",
            "vendor/openssl-zig/crypto/camellia/cmll_cfb.c",
            "vendor/openssl-zig/crypto/camellia/cmll_ctr.c",
            "vendor/openssl-zig/crypto/camellia/cmll_ecb.c",
            "vendor/openssl-zig/crypto/camellia/cmll_misc.c",
            "vendor/openssl-zig/crypto/camellia/cmll_ofb.c",
            "vendor/openssl-zig/crypto/cast/c_cfb64.c",
            "vendor/openssl-zig/crypto/cast/c_ecb.c",
            "vendor/openssl-zig/crypto/cast/c_enc.c",
            "vendor/openssl-zig/crypto/cast/c_ofb64.c",
            "vendor/openssl-zig/crypto/cast/c_skey.c",
            "vendor/openssl-zig/crypto/chacha/chacha_enc.c",
            "vendor/openssl-zig/crypto/chacha/chacha_ppc.c",
            "vendor/openssl-zig/crypto/cmac/cmac.c",
            "vendor/openssl-zig/crypto/cmp/cmp_asn.c",
            "vendor/openssl-zig/crypto/cmp/cmp_client.c",
            "vendor/openssl-zig/crypto/cmp/cmp_ctx.c",
            "vendor/openssl-zig/crypto/cmp/cmp_err.c",
            "vendor/openssl-zig/crypto/cmp/cmp_hdr.c",
            "vendor/openssl-zig/crypto/cmp/cmp_http.c",
            "vendor/openssl-zig/crypto/cmp/cmp_msg.c",
            "vendor/openssl-zig/crypto/cmp/cmp_protect.c",
            "vendor/openssl-zig/crypto/cmp/cmp_server.c",
            "vendor/openssl-zig/crypto/cmp/cmp_status.c",
            "vendor/openssl-zig/crypto/cmp/cmp_util.c",
            "vendor/openssl-zig/crypto/cmp/cmp_vfy.c",
            "vendor/openssl-zig/crypto/cms/cms_asn1.c",
            "vendor/openssl-zig/crypto/cms/cms_att.c",
            "vendor/openssl-zig/crypto/cms/cms_cd.c",
            "vendor/openssl-zig/crypto/cms/cms_dd.c",
            "vendor/openssl-zig/crypto/cms/cms_dh.c",
            "vendor/openssl-zig/crypto/cms/cms_ec.c",
            "vendor/openssl-zig/crypto/cms/cms_enc.c",
            "vendor/openssl-zig/crypto/cms/cms_env.c",
            "vendor/openssl-zig/crypto/cms/cms_err.c",
            "vendor/openssl-zig/crypto/cms/cms_ess.c",
            "vendor/openssl-zig/crypto/cms/cms_io.c",
            "vendor/openssl-zig/crypto/cms/cms_kari.c",
            "vendor/openssl-zig/crypto/cms/cms_lib.c",
            "vendor/openssl-zig/crypto/cms/cms_pwri.c",
            "vendor/openssl-zig/crypto/cms/cms_rsa.c",
            "vendor/openssl-zig/crypto/cms/cms_sd.c",
            "vendor/openssl-zig/crypto/cms/cms_smime.c",
            "vendor/openssl-zig/crypto/comp/c_brotli.c",
            "vendor/openssl-zig/crypto/comp/c_zlib.c",
            "vendor/openssl-zig/crypto/comp/c_zstd.c",
            "vendor/openssl-zig/crypto/comp/comp_err.c",
            "vendor/openssl-zig/crypto/comp/comp_lib.c",
            "vendor/openssl-zig/crypto/conf/conf_api.c",
            "vendor/openssl-zig/crypto/conf/conf_def.c",
            "vendor/openssl-zig/crypto/conf/conf_err.c",
            "vendor/openssl-zig/crypto/conf/conf_lib.c",
            "vendor/openssl-zig/crypto/conf/conf_mall.c",
            "vendor/openssl-zig/crypto/conf/conf_mod.c",
            "vendor/openssl-zig/crypto/conf/conf_sap.c",
            "vendor/openssl-zig/crypto/conf/conf_ssl.c",
            "vendor/openssl-zig/crypto/context.c",
            "vendor/openssl-zig/crypto/core_algorithm.c",
            "vendor/openssl-zig/crypto/core_fetch.c",
            "vendor/openssl-zig/crypto/core_namemap.c",
            "vendor/openssl-zig/crypto/cpt_err.c",
            "vendor/openssl-zig/crypto/crmf/crmf_asn.c",
            "vendor/openssl-zig/crypto/crmf/crmf_err.c",
            "vendor/openssl-zig/crypto/crmf/crmf_lib.c",
            "vendor/openssl-zig/crypto/crmf/crmf_pbm.c",
            "vendor/openssl-zig/crypto/cryptlib.c",
            "vendor/openssl-zig/crypto/ct/ct_b64.c",
            "vendor/openssl-zig/crypto/ct/ct_err.c",
            "vendor/openssl-zig/crypto/ct/ct_log.c",
            "vendor/openssl-zig/crypto/ct/ct_oct.c",
            "vendor/openssl-zig/crypto/ct/ct_policy.c",
            "vendor/openssl-zig/crypto/ct/ct_prn.c",
            "vendor/openssl-zig/crypto/ct/ct_sct.c",
            "vendor/openssl-zig/crypto/ct/ct_sct_ctx.c",
            "vendor/openssl-zig/crypto/ct/ct_vfy.c",
            "vendor/openssl-zig/crypto/ct/ct_x509v3.c",
            "vendor/openssl-zig/crypto/ctype.c",
            "vendor/openssl-zig/crypto/cversion.c",
            "vendor/openssl-zig/crypto/der_writer.c",
            "vendor/openssl-zig/crypto/des/cbc_cksm.c",
            "vendor/openssl-zig/crypto/des/cbc_enc.c",
            "vendor/openssl-zig/crypto/des/cfb64ede.c",
            "vendor/openssl-zig/crypto/des/cfb64enc.c",
            "vendor/openssl-zig/crypto/des/cfb_enc.c",
            "vendor/openssl-zig/crypto/des/des_enc.c",
            "vendor/openssl-zig/crypto/des/ecb3_enc.c",
            "vendor/openssl-zig/crypto/des/ecb_enc.c",
            "vendor/openssl-zig/crypto/des/fcrypt.c",
            "vendor/openssl-zig/crypto/des/fcrypt_b.c",
            "vendor/openssl-zig/crypto/des/ncbc_enc.c",
            "vendor/openssl-zig/crypto/des/ofb64ede.c",
            "vendor/openssl-zig/crypto/des/ofb64enc.c",
            "vendor/openssl-zig/crypto/des/ofb_enc.c",
            "vendor/openssl-zig/crypto/des/pcbc_enc.c",
            "vendor/openssl-zig/crypto/des/qud_cksm.c",
            "vendor/openssl-zig/crypto/des/rand_key.c",
            "vendor/openssl-zig/crypto/des/set_key.c",
            "vendor/openssl-zig/crypto/des/str2key.c",
            "vendor/openssl-zig/crypto/des/xcbc_enc.c",
            "vendor/openssl-zig/crypto/deterministic_nonce.c",
            "vendor/openssl-zig/crypto/dh/dh_ameth.c",
            "vendor/openssl-zig/crypto/dh/dh_asn1.c",
            "vendor/openssl-zig/crypto/dh/dh_backend.c",
            "vendor/openssl-zig/crypto/dh/dh_check.c",
            "vendor/openssl-zig/crypto/dh/dh_depr.c",
            "vendor/openssl-zig/crypto/dh/dh_err.c",
            "vendor/openssl-zig/crypto/dh/dh_gen.c",
            "vendor/openssl-zig/crypto/dh/dh_group_params.c",
            "vendor/openssl-zig/crypto/dh/dh_kdf.c",
            "vendor/openssl-zig/crypto/dh/dh_key.c",
            "vendor/openssl-zig/crypto/dh/dh_lib.c",
            "vendor/openssl-zig/crypto/dh/dh_meth.c",
            "vendor/openssl-zig/crypto/dh/dh_pmeth.c",
            "vendor/openssl-zig/crypto/dh/dh_prn.c",
            "vendor/openssl-zig/crypto/dh/dh_rfc5114.c",
            "vendor/openssl-zig/crypto/dllmain.c",
            "vendor/openssl-zig/crypto/dsa/dsa_ameth.c",
            "vendor/openssl-zig/crypto/dsa/dsa_asn1.c",
            "vendor/openssl-zig/crypto/dsa/dsa_backend.c",
            "vendor/openssl-zig/crypto/dsa/dsa_check.c",
            "vendor/openssl-zig/crypto/dsa/dsa_depr.c",
            "vendor/openssl-zig/crypto/dsa/dsa_err.c",
            "vendor/openssl-zig/crypto/dsa/dsa_gen.c",
            "vendor/openssl-zig/crypto/dsa/dsa_key.c",
            "vendor/openssl-zig/crypto/dsa/dsa_lib.c",
            "vendor/openssl-zig/crypto/dsa/dsa_meth.c",
            "vendor/openssl-zig/crypto/dsa/dsa_ossl.c",
            "vendor/openssl-zig/crypto/dsa/dsa_pmeth.c",
            "vendor/openssl-zig/crypto/dsa/dsa_prn.c",
            "vendor/openssl-zig/crypto/dsa/dsa_sign.c",
            "vendor/openssl-zig/crypto/dsa/dsa_vrf.c",
            "vendor/openssl-zig/crypto/dso/dso_dl.c",
            "vendor/openssl-zig/crypto/dso/dso_dlfcn.c",
            "vendor/openssl-zig/crypto/dso/dso_err.c",
            "vendor/openssl-zig/crypto/dso/dso_lib.c",
            "vendor/openssl-zig/crypto/dso/dso_openssl.c",
            // "crypto/dso/dso_vms.c",
            // "crypto/dso/dso_win32.c",
            "vendor/openssl-zig/crypto/ebcdic.c",
            "vendor/openssl-zig/crypto/ec/curve25519.c",
            "vendor/openssl-zig/crypto/ec/curve448/arch_32/f_impl32.c",
            "vendor/openssl-zig/crypto/ec/curve448/arch_64/f_impl64.c",
            "vendor/openssl-zig/crypto/ec/curve448/curve448.c",
            "vendor/openssl-zig/crypto/ec/curve448/curve448_tables.c",
            "vendor/openssl-zig/crypto/ec/curve448/eddsa.c",
            "vendor/openssl-zig/crypto/ec/curve448/f_generic.c",
            "vendor/openssl-zig/crypto/ec/curve448/scalar.c",
            "vendor/openssl-zig/crypto/ec/ec2_oct.c",
            "vendor/openssl-zig/crypto/ec/ec2_smpl.c",
            "vendor/openssl-zig/crypto/ec/ec_ameth.c",
            "vendor/openssl-zig/crypto/ec/ec_asn1.c",
            "vendor/openssl-zig/crypto/ec/ec_backend.c",
            "vendor/openssl-zig/crypto/ec/ec_check.c",
            "vendor/openssl-zig/crypto/ec/ec_curve.c",
            "vendor/openssl-zig/crypto/ec/ec_cvt.c",
            "vendor/openssl-zig/crypto/ec/ec_deprecated.c",
            "vendor/openssl-zig/crypto/ec/ec_err.c",
            "vendor/openssl-zig/crypto/ec/ec_key.c",
            "vendor/openssl-zig/crypto/ec/ec_kmeth.c",
            "vendor/openssl-zig/crypto/ec/ec_lib.c",
            "vendor/openssl-zig/crypto/ec/ec_mult.c",
            "vendor/openssl-zig/crypto/ec/ec_oct.c",
            "vendor/openssl-zig/crypto/ec/ec_pmeth.c",
            "vendor/openssl-zig/crypto/ec/ec_print.c",
            "vendor/openssl-zig/crypto/ec/ecdh_kdf.c",
            "vendor/openssl-zig/crypto/ec/ecdh_ossl.c",
            "vendor/openssl-zig/crypto/ec/ecdsa_ossl.c",
            "vendor/openssl-zig/crypto/ec/ecdsa_sign.c",
            "vendor/openssl-zig/crypto/ec/ecdsa_vrf.c",
            "vendor/openssl-zig/crypto/ec/eck_prn.c",
            "vendor/openssl-zig/crypto/ec/ecp_mont.c",
            "vendor/openssl-zig/crypto/ec/ecp_nist.c",
            // "crypto/ec/ecp_nistp224.c",
            // "crypto/ec/ecp_nistp256.c",
            // "crypto/ec/ecp_nistp521.c",
            "vendor/openssl-zig/crypto/ec/ecp_nistputil.c",
            // "crypto/ec/ecp_nistz256.c",
            // "crypto/ec/ecp_nistz256_table.c",
            "vendor/openssl-zig/crypto/ec/ecp_oct.c",
            "vendor/openssl-zig/crypto/ec/ecp_ppc.c",
            "vendor/openssl-zig/crypto/ec/ecp_smpl.c",
            "vendor/openssl-zig/crypto/ec/ecx_backend.c",
            "vendor/openssl-zig/crypto/ec/ecx_key.c",
            "vendor/openssl-zig/crypto/ec/ecx_meth.c",
            "vendor/openssl-zig/crypto/encode_decode/decoder_err.c",
            "vendor/openssl-zig/crypto/encode_decode/decoder_lib.c",
            "vendor/openssl-zig/crypto/encode_decode/decoder_meth.c",
            "vendor/openssl-zig/crypto/encode_decode/decoder_pkey.c",
            "vendor/openssl-zig/crypto/encode_decode/encoder_err.c",
            "vendor/openssl-zig/crypto/encode_decode/encoder_lib.c",
            "vendor/openssl-zig/crypto/encode_decode/encoder_meth.c",
            "vendor/openssl-zig/crypto/encode_decode/encoder_pkey.c",
            // "crypto/engine/eng_all.c",
            // "crypto/engine/eng_cnf.c",
            // "crypto/engine/eng_ctrl.c",
            // "crypto/engine/eng_dyn.c",
            // "crypto/engine/eng_err.c",
            // "crypto/engine/eng_fat.c",
            // "crypto/engine/eng_init.c",
            // "crypto/engine/eng_lib.c",
            // "crypto/engine/eng_list.c",
            // "crypto/engine/eng_openssl.c",
            // "crypto/engine/eng_pkey.c",
            // "crypto/engine/eng_rdrand.c",
            // "crypto/engine/eng_table.c",
            // "crypto/engine/tb_asnmth.c",
            // "crypto/engine/tb_cipher.c",
            // "crypto/engine/tb_dh.c",
            // "crypto/engine/tb_digest.c",
            // "crypto/engine/tb_dsa.c",
            // "crypto/engine/tb_eckey.c",
            // "crypto/engine/tb_pkmeth.c",
            // "crypto/engine/tb_rand.c",
            // "crypto/engine/tb_rsa.c",
            "vendor/openssl-zig/crypto/err/err.c",
            "vendor/openssl-zig/crypto/err/err_all.c",
            "vendor/openssl-zig/crypto/err/err_all_legacy.c",
            "vendor/openssl-zig/crypto/err/err_blocks.c",
            "vendor/openssl-zig/crypto/err/err_mark.c",
            "vendor/openssl-zig/crypto/err/err_prn.c",
            "vendor/openssl-zig/crypto/ess/ess_asn1.c",
            "vendor/openssl-zig/crypto/ess/ess_err.c",
            "vendor/openssl-zig/crypto/ess/ess_lib.c",
            "vendor/openssl-zig/crypto/evp/asymcipher.c",
            "vendor/openssl-zig/crypto/evp/bio_b64.c",
            "vendor/openssl-zig/crypto/evp/bio_enc.c",
            "vendor/openssl-zig/crypto/evp/bio_md.c",
            "vendor/openssl-zig/crypto/evp/bio_ok.c",
            "vendor/openssl-zig/crypto/evp/c_allc.c",
            "vendor/openssl-zig/crypto/evp/c_alld.c",
            "vendor/openssl-zig/crypto/evp/cmeth_lib.c",
            "vendor/openssl-zig/crypto/evp/ctrl_params_translate.c",
            "vendor/openssl-zig/crypto/evp/dh_ctrl.c",
            "vendor/openssl-zig/crypto/evp/dh_support.c",
            "vendor/openssl-zig/crypto/evp/digest.c",
            "vendor/openssl-zig/crypto/evp/dsa_ctrl.c",
            "vendor/openssl-zig/crypto/evp/e_aes.c",
            "vendor/openssl-zig/crypto/evp/e_aes_cbc_hmac_sha1.c",
            "vendor/openssl-zig/crypto/evp/e_aes_cbc_hmac_sha256.c",
            "vendor/openssl-zig/crypto/evp/e_aria.c",
            "vendor/openssl-zig/crypto/evp/e_bf.c",
            "vendor/openssl-zig/crypto/evp/e_camellia.c",
            "vendor/openssl-zig/crypto/evp/e_cast.c",
            "vendor/openssl-zig/crypto/evp/e_chacha20_poly1305.c",
            "vendor/openssl-zig/crypto/evp/e_des.c",
            "vendor/openssl-zig/crypto/evp/e_des3.c",
            "vendor/openssl-zig/crypto/evp/e_idea.c",
            "vendor/openssl-zig/crypto/evp/e_null.c",
            "vendor/openssl-zig/crypto/evp/e_old.c",
            "vendor/openssl-zig/crypto/evp/e_rc2.c",
            "vendor/openssl-zig/crypto/evp/e_rc4.c",
            "vendor/openssl-zig/crypto/evp/e_rc4_hmac_md5.c",
            "vendor/openssl-zig/crypto/evp/e_rc5.c",
            "vendor/openssl-zig/crypto/evp/e_seed.c",
            "vendor/openssl-zig/crypto/evp/e_sm4.c",
            "vendor/openssl-zig/crypto/evp/e_xcbc_d.c",
            "vendor/openssl-zig/crypto/evp/ec_ctrl.c",
            "vendor/openssl-zig/crypto/evp/ec_support.c",
            "vendor/openssl-zig/crypto/evp/encode.c",
            "vendor/openssl-zig/crypto/evp/evp_cnf.c",
            "vendor/openssl-zig/crypto/evp/evp_enc.c",
            "vendor/openssl-zig/crypto/evp/evp_err.c",
            "vendor/openssl-zig/crypto/evp/evp_fetch.c",
            "vendor/openssl-zig/crypto/evp/evp_key.c",
            // "crypto/evp/evp_lib.c",
            "vendor/openssl-zig/crypto/evp/evp_pbe.c",
            "vendor/openssl-zig/crypto/evp/evp_pkey.c",
            "vendor/openssl-zig/crypto/evp/evp_rand.c",
            "vendor/openssl-zig/crypto/evp/evp_utils.c",
            "vendor/openssl-zig/crypto/evp/exchange.c",
            "vendor/openssl-zig/crypto/evp/kdf_lib.c",
            "vendor/openssl-zig/crypto/evp/kdf_meth.c",
            "vendor/openssl-zig/crypto/evp/kem.c",
            "vendor/openssl-zig/crypto/evp/keymgmt_lib.c",
            "vendor/openssl-zig/crypto/evp/keymgmt_meth.c",
            "vendor/openssl-zig/crypto/evp/legacy_blake2.c",
            // "crypto/evp/legacy_md2.c",
            "vendor/openssl-zig/crypto/evp/legacy_md4.c",
            "vendor/openssl-zig/crypto/evp/legacy_md5.c",
            "vendor/openssl-zig/crypto/evp/legacy_md5_sha1.c",
            "vendor/openssl-zig/crypto/evp/legacy_mdc2.c",
            "vendor/openssl-zig/crypto/evp/legacy_ripemd.c",
            "vendor/openssl-zig/crypto/evp/legacy_sha.c",
            "vendor/openssl-zig/crypto/evp/legacy_wp.c",
            "vendor/openssl-zig/crypto/evp/m_null.c",
            "vendor/openssl-zig/crypto/evp/m_sigver.c",
            "vendor/openssl-zig/crypto/evp/mac_lib.c",
            "vendor/openssl-zig/crypto/evp/mac_meth.c",
            "vendor/openssl-zig/crypto/evp/names.c",
            "vendor/openssl-zig/crypto/evp/p5_crpt.c",
            "vendor/openssl-zig/crypto/evp/p5_crpt2.c",
            "vendor/openssl-zig/crypto/evp/p_dec.c",
            "vendor/openssl-zig/crypto/evp/p_enc.c",
            "vendor/openssl-zig/crypto/evp/p_legacy.c",
            "vendor/openssl-zig/crypto/evp/p_lib.c",
            "vendor/openssl-zig/crypto/evp/p_open.c",
            "vendor/openssl-zig/crypto/evp/p_seal.c",
            "vendor/openssl-zig/crypto/evp/p_sign.c",
            "vendor/openssl-zig/crypto/evp/p_verify.c",
            "vendor/openssl-zig/crypto/evp/pbe_scrypt.c",
            "vendor/openssl-zig/crypto/evp/pmeth_check.c",
            "vendor/openssl-zig/crypto/evp/pmeth_gn.c",
            "vendor/openssl-zig/crypto/evp/pmeth_lib.c",
            // "crypto/evp/signature.c",
            "vendor/openssl-zig/crypto/ex_data.c",
            "vendor/openssl-zig/crypto/ffc/ffc_backend.c",
            "vendor/openssl-zig/crypto/ffc/ffc_dh.c",
            "vendor/openssl-zig/crypto/ffc/ffc_key_generate.c",
            "vendor/openssl-zig/crypto/ffc/ffc_key_validate.c",
            "vendor/openssl-zig/crypto/ffc/ffc_params.c",
            "vendor/openssl-zig/crypto/ffc/ffc_params_generate.c",
            "vendor/openssl-zig/crypto/ffc/ffc_params_validate.c",
            "vendor/openssl-zig/crypto/getenv.c",
            "vendor/openssl-zig/crypto/hmac/hmac.c",
            "vendor/openssl-zig/crypto/hpke/hpke.c",
            "vendor/openssl-zig/crypto/hpke/hpke_util.c",
            "vendor/openssl-zig/crypto/http/http_client.c",
            "vendor/openssl-zig/crypto/http/http_err.c",
            "vendor/openssl-zig/crypto/http/http_lib.c",
            "vendor/openssl-zig/crypto/idea/i_cbc.c",
            "vendor/openssl-zig/crypto/idea/i_cfb64.c",
            "vendor/openssl-zig/crypto/idea/i_ecb.c",
            "vendor/openssl-zig/crypto/idea/i_ofb64.c",
            "vendor/openssl-zig/crypto/idea/i_skey.c",
            "vendor/openssl-zig/crypto/info.c",
            "vendor/openssl-zig/crypto/init.c",
            "vendor/openssl-zig/crypto/initthread.c",
            "vendor/openssl-zig/crypto/kdf/kdf_err.c",
            "vendor/openssl-zig/crypto/lhash/lh_stats.c",
            "vendor/openssl-zig/crypto/lhash/lhash.c",
            // "crypto/loongarchcap.c",
            // "crypto/md2/md2_dgst.c",
            // "crypto/md2/md2_one.c",
            "vendor/openssl-zig/crypto/md4/md4_dgst.c",
            "vendor/openssl-zig/crypto/md4/md4_one.c",
            "vendor/openssl-zig/crypto/md5/md5_dgst.c",
            "vendor/openssl-zig/crypto/md5/md5_one.c",
            "vendor/openssl-zig/crypto/md5/md5_sha1.c",
            "vendor/openssl-zig/crypto/mdc2/mdc2_one.c",
            "vendor/openssl-zig/crypto/mdc2/mdc2dgst.c",
            "vendor/openssl-zig/crypto/mem.c",
            "vendor/openssl-zig/crypto/mem_clr.c",
            "vendor/openssl-zig/crypto/mem_sec.c",
            "vendor/openssl-zig/crypto/modes/cbc128.c",
            "vendor/openssl-zig/crypto/modes/ccm128.c",
            "vendor/openssl-zig/crypto/modes/cfb128.c",
            "vendor/openssl-zig/crypto/modes/ctr128.c",
            "vendor/openssl-zig/crypto/modes/cts128.c",
            "vendor/openssl-zig/crypto/modes/gcm128.c",
            "vendor/openssl-zig/crypto/modes/ocb128.c",
            "vendor/openssl-zig/crypto/modes/ofb128.c",
            "vendor/openssl-zig/crypto/modes/siv128.c",
            "vendor/openssl-zig/crypto/modes/wrap128.c",
            "vendor/openssl-zig/crypto/modes/xts128.c",
            "vendor/openssl-zig/crypto/modes/xts128gb.c",
            "vendor/openssl-zig/crypto/o_dir.c",
            "vendor/openssl-zig/crypto/o_fopen.c",
            "vendor/openssl-zig/crypto/o_init.c",
            "vendor/openssl-zig/crypto/o_str.c",
            "vendor/openssl-zig/crypto/o_time.c",
            "vendor/openssl-zig/crypto/objects/o_names.c",
            "vendor/openssl-zig/crypto/objects/obj_dat.c",
            "vendor/openssl-zig/crypto/objects/obj_err.c",
            "vendor/openssl-zig/crypto/objects/obj_lib.c",
            "vendor/openssl-zig/crypto/objects/obj_xref.c",
            "vendor/openssl-zig/crypto/ocsp/ocsp_asn.c",
            "vendor/openssl-zig/crypto/ocsp/ocsp_cl.c",
            "vendor/openssl-zig/crypto/ocsp/ocsp_err.c",
            "vendor/openssl-zig/crypto/ocsp/ocsp_ext.c",
            "vendor/openssl-zig/crypto/ocsp/ocsp_http.c",
            "vendor/openssl-zig/crypto/ocsp/ocsp_lib.c",
            "vendor/openssl-zig/crypto/ocsp/ocsp_prn.c",
            "vendor/openssl-zig/crypto/ocsp/ocsp_srv.c",
            "vendor/openssl-zig/crypto/ocsp/ocsp_vfy.c",
            "vendor/openssl-zig/crypto/ocsp/v3_ocsp.c",
            "vendor/openssl-zig/crypto/packet.c",
            "vendor/openssl-zig/crypto/param_build.c",
            "vendor/openssl-zig/crypto/param_build_set.c",
            "vendor/openssl-zig/crypto/params.c",
            "vendor/openssl-zig/crypto/params_dup.c",
            "vendor/openssl-zig/crypto/params_from_text.c",
            "vendor/openssl-zig/crypto/passphrase.c",
            "vendor/openssl-zig/crypto/pem/pem_all.c",
            "vendor/openssl-zig/crypto/pem/pem_err.c",
            "vendor/openssl-zig/crypto/pem/pem_info.c",
            "vendor/openssl-zig/crypto/pem/pem_lib.c",
            "vendor/openssl-zig/crypto/pem/pem_oth.c",
            "vendor/openssl-zig/crypto/pem/pem_pk8.c",
            "vendor/openssl-zig/crypto/pem/pem_pkey.c",
            "vendor/openssl-zig/crypto/pem/pem_sign.c",
            "vendor/openssl-zig/crypto/pem/pem_x509.c",
            "vendor/openssl-zig/crypto/pem/pem_xaux.c",
            "vendor/openssl-zig/crypto/pem/pvkfmt.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_add.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_asn.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_attr.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_crpt.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_crt.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_decr.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_init.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_key.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_kiss.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_mutl.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_npas.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_p8d.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_p8e.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_sbag.c",
            "vendor/openssl-zig/crypto/pkcs12/p12_utl.c",
            "vendor/openssl-zig/crypto/pkcs12/pk12err.c",
            "vendor/openssl-zig/crypto/pkcs7/bio_pk7.c",
            "vendor/openssl-zig/crypto/pkcs7/pk7_asn1.c",
            "vendor/openssl-zig/crypto/pkcs7/pk7_attr.c",
            "vendor/openssl-zig/crypto/pkcs7/pk7_doit.c",
            "vendor/openssl-zig/crypto/pkcs7/pk7_lib.c",
            "vendor/openssl-zig/crypto/pkcs7/pk7_mime.c",
            "vendor/openssl-zig/crypto/pkcs7/pk7_smime.c",
            "vendor/openssl-zig/crypto/pkcs7/pkcs7err.c",
            "vendor/openssl-zig/crypto/poly1305/poly1305.c",
            // "crypto/poly1305/poly1305_base2_44.c",
            // "crypto/poly1305/poly1305_ieee754.c",
            "vendor/openssl-zig/crypto/poly1305/poly1305_ppc.c",
            "vendor/openssl-zig/crypto/property/defn_cache.c",
            "vendor/openssl-zig/crypto/property/property.c",
            "vendor/openssl-zig/crypto/property/property_err.c",
            "vendor/openssl-zig/crypto/property/property_parse.c",
            "vendor/openssl-zig/crypto/property/property_query.c",
            "vendor/openssl-zig/crypto/property/property_string.c",
            "vendor/openssl-zig/crypto/provider.c",
            "vendor/openssl-zig/crypto/provider_child.c",
            "vendor/openssl-zig/crypto/provider_conf.c",
            "vendor/openssl-zig/crypto/provider_core.c",
            "vendor/openssl-zig/crypto/provider_predefined.c",
            "vendor/openssl-zig/crypto/punycode.c",
            "vendor/openssl-zig/crypto/quic_vlint.c",
            "vendor/openssl-zig/crypto/rand/prov_seed.c",
            "vendor/openssl-zig/crypto/rand/rand_deprecated.c",
            // "crypto/rand/rand_egd.c",
            "vendor/openssl-zig/crypto/rand/rand_err.c",
            "vendor/openssl-zig/crypto/rand/rand_lib.c",
            "vendor/openssl-zig/crypto/rand/rand_meth.c",
            "vendor/openssl-zig/crypto/rand/rand_pool.c",
            "vendor/openssl-zig/crypto/rand/randfile.c",
            "vendor/openssl-zig/crypto/rc2/rc2_cbc.c",
            "vendor/openssl-zig/crypto/rc2/rc2_ecb.c",
            "vendor/openssl-zig/crypto/rc2/rc2_skey.c",
            "vendor/openssl-zig/crypto/rc2/rc2cfb64.c",
            "vendor/openssl-zig/crypto/rc2/rc2ofb64.c",
            "vendor/openssl-zig/crypto/rc4/rc4_enc.c",
            "vendor/openssl-zig/crypto/rc4/rc4_skey.c",
            // "crypto/rc5/rc5_ecb.c",
            // "crypto/rc5/rc5_enc.c",
            // "crypto/rc5/rc5_skey.c",
            // "crypto/rc5/rc5cfb64.c",
            // "crypto/rc5/rc5ofb64.c",
            "vendor/openssl-zig/crypto/ripemd/rmd_dgst.c",
            "vendor/openssl-zig/crypto/ripemd/rmd_one.c",
            // "crypto/rsa/rsa_acvp_test_params.c",
            "vendor/openssl-zig/crypto/rsa/rsa_ameth.c",
            "vendor/openssl-zig/crypto/rsa/rsa_asn1.c",
            "vendor/openssl-zig/crypto/rsa/rsa_backend.c",
            "vendor/openssl-zig/crypto/rsa/rsa_chk.c",
            "vendor/openssl-zig/crypto/rsa/rsa_crpt.c",
            "vendor/openssl-zig/crypto/rsa/rsa_depr.c",
            "vendor/openssl-zig/crypto/rsa/rsa_err.c",
            "vendor/openssl-zig/crypto/rsa/rsa_gen.c",
            "vendor/openssl-zig/crypto/rsa/rsa_lib.c",
            "vendor/openssl-zig/crypto/rsa/rsa_meth.c",
            "vendor/openssl-zig/crypto/rsa/rsa_mp.c",
            "vendor/openssl-zig/crypto/rsa/rsa_mp_names.c",
            "vendor/openssl-zig/crypto/rsa/rsa_none.c",
            "vendor/openssl-zig/crypto/rsa/rsa_oaep.c",
            "vendor/openssl-zig/crypto/rsa/rsa_ossl.c",
            "vendor/openssl-zig/crypto/rsa/rsa_pk1.c",
            "vendor/openssl-zig/crypto/rsa/rsa_pmeth.c",
            "vendor/openssl-zig/crypto/rsa/rsa_prn.c",
            "vendor/openssl-zig/crypto/rsa/rsa_pss.c",
            "vendor/openssl-zig/crypto/rsa/rsa_saos.c",
            "vendor/openssl-zig/crypto/rsa/rsa_schemes.c",
            "vendor/openssl-zig/crypto/rsa/rsa_sign.c",
            "vendor/openssl-zig/crypto/rsa/rsa_sp800_56b_check.c",
            "vendor/openssl-zig/crypto/rsa/rsa_sp800_56b_gen.c",
            "vendor/openssl-zig/crypto/rsa/rsa_x931.c",
            "vendor/openssl-zig/crypto/rsa/rsa_x931g.c",
            "vendor/openssl-zig/crypto/seed/seed.c",
            "vendor/openssl-zig/crypto/seed/seed_cbc.c",
            "vendor/openssl-zig/crypto/seed/seed_cfb.c",
            "vendor/openssl-zig/crypto/seed/seed_ecb.c",
            "vendor/openssl-zig/crypto/seed/seed_ofb.c",
            "vendor/openssl-zig/crypto/self_test_core.c",
            "vendor/openssl-zig/crypto/sha/keccak1600.c",
            "vendor/openssl-zig/crypto/sha/sha1_one.c",
            "vendor/openssl-zig/crypto/sha/sha1dgst.c",
            "vendor/openssl-zig/crypto/sha/sha256.c",
            "vendor/openssl-zig/crypto/sha/sha3.c",
            "vendor/openssl-zig/crypto/sha/sha512.c",
            "vendor/openssl-zig/crypto/sha/sha_ppc.c",
            "vendor/openssl-zig/crypto/siphash/siphash.c",
            "vendor/openssl-zig/crypto/sleep.c",
            "vendor/openssl-zig/crypto/sm2/sm2_crypt.c",
            "vendor/openssl-zig/crypto/sm2/sm2_err.c",
            "vendor/openssl-zig/crypto/sm2/sm2_key.c",
            "vendor/openssl-zig/crypto/sm2/sm2_sign.c",
            "vendor/openssl-zig/crypto/sm3/legacy_sm3.c",
            "vendor/openssl-zig/crypto/sm3/sm3.c",
            "vendor/openssl-zig/crypto/sm4/sm4.c",
            "vendor/openssl-zig/crypto/sparse_array.c",
            "vendor/openssl-zig/crypto/srp/srp_lib.c",
            "vendor/openssl-zig/crypto/srp/srp_vfy.c",
            "vendor/openssl-zig/crypto/stack/stack.c",
            "vendor/openssl-zig/crypto/store/store_err.c",
            "vendor/openssl-zig/crypto/store/store_init.c",
            "vendor/openssl-zig/crypto/store/store_lib.c",
            "vendor/openssl-zig/crypto/store/store_meth.c",
            "vendor/openssl-zig/crypto/store/store_register.c",
            "vendor/openssl-zig/crypto/store/store_result.c",
            "vendor/openssl-zig/crypto/store/store_strings.c",
            "vendor/openssl-zig/crypto/thread/api.c",
            "vendor/openssl-zig/crypto/thread/arch.c",
            "vendor/openssl-zig/crypto/thread/arch/thread_none.c",
            if (lib.rootModuleTarget().os.tag == .windows)
                "vendor/openssl-zig/crypto/thread/arch/thread_win.c"
            else
                "vendor/openssl-zig/crypto/thread/arch/thread_posix.c",
            "vendor/openssl-zig/crypto/thread/internal.c",
            "vendor/openssl-zig/crypto/threads_lib.c",
            "vendor/openssl-zig/crypto/threads_none.c",
            if (lib.rootModuleTarget().os.tag == .windows)
                "vendor/openssl-zig/crypto/threads_win.c"
            else
                "vendor/openssl-zig/crypto/threads_pthread.c",
            "vendor/openssl-zig/crypto/time.c",
            "vendor/openssl-zig/crypto/trace.c",
            "vendor/openssl-zig/crypto/ts/ts_asn1.c",
            "vendor/openssl-zig/crypto/ts/ts_conf.c",
            "vendor/openssl-zig/crypto/ts/ts_err.c",
            "vendor/openssl-zig/crypto/ts/ts_lib.c",
            "vendor/openssl-zig/crypto/ts/ts_req_print.c",
            "vendor/openssl-zig/crypto/ts/ts_req_utils.c",
            "vendor/openssl-zig/crypto/ts/ts_rsp_print.c",
            "vendor/openssl-zig/crypto/ts/ts_rsp_sign.c",
            "vendor/openssl-zig/crypto/ts/ts_rsp_utils.c",
            "vendor/openssl-zig/crypto/ts/ts_rsp_verify.c",
            "vendor/openssl-zig/crypto/ts/ts_verify_ctx.c",
            "vendor/openssl-zig/crypto/txt_db/txt_db.c",
            "vendor/openssl-zig/crypto/ui/ui_err.c",
            "vendor/openssl-zig/crypto/ui/ui_lib.c",
            "vendor/openssl-zig/crypto/ui/ui_null.c",
            "vendor/openssl-zig/crypto/ui/ui_openssl.c",
            "vendor/openssl-zig/crypto/ui/ui_util.c",
            "vendor/openssl-zig/crypto/uid.c",
            "vendor/openssl-zig/crypto/whrlpool/wp_block.c",
            "vendor/openssl-zig/crypto/whrlpool/wp_dgst.c",
            "vendor/openssl-zig/crypto/x509/by_dir.c",
            "vendor/openssl-zig/crypto/x509/by_file.c",
            "vendor/openssl-zig/crypto/x509/by_store.c",
            "vendor/openssl-zig/crypto/x509/pcy_cache.c",
            "vendor/openssl-zig/crypto/x509/pcy_data.c",
            "vendor/openssl-zig/crypto/x509/pcy_lib.c",
            "vendor/openssl-zig/crypto/x509/pcy_map.c",
            "vendor/openssl-zig/crypto/x509/pcy_node.c",
            "vendor/openssl-zig/crypto/x509/pcy_tree.c",
            "vendor/openssl-zig/crypto/x509/t_crl.c",
            "vendor/openssl-zig/crypto/x509/t_req.c",
            "vendor/openssl-zig/crypto/x509/t_x509.c",
            "vendor/openssl-zig/crypto/x509/v3_addr.c",
            "vendor/openssl-zig/crypto/x509/v3_admis.c",
            "vendor/openssl-zig/crypto/x509/v3_akeya.c",
            "vendor/openssl-zig/crypto/x509/v3_akid.c",
            "vendor/openssl-zig/crypto/x509/v3_asid.c",
            "vendor/openssl-zig/crypto/x509/v3_bcons.c",
            "vendor/openssl-zig/crypto/x509/v3_bitst.c",
            "vendor/openssl-zig/crypto/x509/v3_conf.c",
            "vendor/openssl-zig/crypto/x509/v3_cpols.c",
            "vendor/openssl-zig/crypto/x509/v3_crld.c",
            "vendor/openssl-zig/crypto/x509/v3_enum.c",
            "vendor/openssl-zig/crypto/x509/v3_extku.c",
            "vendor/openssl-zig/crypto/x509/v3_genn.c",
            "vendor/openssl-zig/crypto/x509/v3_ia5.c",
            "vendor/openssl-zig/crypto/x509/v3_info.c",
            "vendor/openssl-zig/crypto/x509/v3_int.c",
            "vendor/openssl-zig/crypto/x509/v3_ist.c",
            "vendor/openssl-zig/crypto/x509/v3_lib.c",
            "vendor/openssl-zig/crypto/x509/v3_ncons.c",
            "vendor/openssl-zig/crypto/x509/v3_pci.c",
            "vendor/openssl-zig/crypto/x509/v3_pcia.c",
            "vendor/openssl-zig/crypto/x509/v3_pcons.c",
            "vendor/openssl-zig/crypto/x509/v3_pku.c",
            "vendor/openssl-zig/crypto/x509/v3_pmaps.c",
            "vendor/openssl-zig/crypto/x509/v3_prn.c",
            "vendor/openssl-zig/crypto/x509/v3_purp.c",
            "vendor/openssl-zig/crypto/x509/v3_san.c",
            "vendor/openssl-zig/crypto/x509/v3_skid.c",
            "vendor/openssl-zig/crypto/x509/v3_sxnet.c",
            "vendor/openssl-zig/crypto/x509/v3_tlsf.c",
            "vendor/openssl-zig/crypto/x509/v3_utf8.c",
            "vendor/openssl-zig/crypto/x509/v3_utl.c",
            "vendor/openssl-zig/crypto/x509/v3err.c",
            "vendor/openssl-zig/crypto/x509/x509_att.c",
            "vendor/openssl-zig/crypto/x509/x509_cmp.c",
            "vendor/openssl-zig/crypto/x509/x509_d2.c",
            "vendor/openssl-zig/crypto/x509/x509_def.c",
            "vendor/openssl-zig/crypto/x509/x509_err.c",
            "vendor/openssl-zig/crypto/x509/x509_ext.c",
            "vendor/openssl-zig/crypto/x509/x509_lu.c",
            "vendor/openssl-zig/crypto/x509/x509_meth.c",
            "vendor/openssl-zig/crypto/x509/x509_obj.c",
            "vendor/openssl-zig/crypto/x509/x509_r2x.c",
            "vendor/openssl-zig/crypto/x509/x509_req.c",
            "vendor/openssl-zig/crypto/x509/x509_set.c",
            "vendor/openssl-zig/crypto/x509/x509_trust.c",
            "vendor/openssl-zig/crypto/x509/x509_txt.c",
            "vendor/openssl-zig/crypto/x509/x509_v3.c",
            "vendor/openssl-zig/crypto/x509/x509_vfy.c",
            "vendor/openssl-zig/crypto/x509/x509_vpm.c",
            "vendor/openssl-zig/crypto/x509/x509cset.c",
            "vendor/openssl-zig/crypto/x509/x509name.c",
            "vendor/openssl-zig/crypto/x509/x509rset.c",
            "vendor/openssl-zig/crypto/x509/x509spki.c",
            "vendor/openssl-zig/crypto/x509/x509type.c",
            "vendor/openssl-zig/crypto/x509/x_all.c",
            "vendor/openssl-zig/crypto/x509/x_attrib.c",
            "vendor/openssl-zig/crypto/x509/x_crl.c",
            "vendor/openssl-zig/crypto/x509/x_exten.c",
            "vendor/openssl-zig/crypto/x509/x_name.c",
            "vendor/openssl-zig/crypto/x509/x_pubkey.c",
            "vendor/openssl-zig/crypto/x509/x_req.c",
            "vendor/openssl-zig/crypto/x509/x_x509.c",
            "vendor/openssl-zig/crypto/x509/x_x509a.c",
        },
        .flags = cflags,
    });
    lib.root_module.linkLibrary(libprovider(b, target, optimize));
    lib.linkLibC();
    return lib;
}

fn libssl(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode) *std.Build.Step.Compile {
    const lib = b.addStaticLibrary(.{
        .name = "ssl",
        .target = target,
        .optimize = optimize,
    });
    lib.pie = true;
    switch (optimize) {
        .Debug, .ReleaseSafe => lib.bundle_compiler_rt = true,
        else => lib.root_module.strip = true,
    }
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/include"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/include_gen"));
    lib.root_module.addCMacro("OPENSSL_NO_DEPRECATED", "");
    lib.root_module.addCMacro("OPENSSL_NO_ENGINE", "");
    lib.root_module.addCMacro("OPENSSL_NO_SRP", "");
    lib.root_module.addCMacro("OPENSSL_NO_UI_CONSOLE", "");
    lib.root_module.addCMacro("OPENSSL_NO_ASAN", "");
    lib.root_module.addCMacro("OPENSSL_NO_ASM", "");
    lib.root_module.addCMacro("OPENSSL_NO_KTLS", "");
    lib.root_module.addCMacro("OPENSSL_NO_QUIC", "");
    lib.root_module.addCMacro("OPENSSL_NO_QLOG", "");
    if (lib.rootModuleTarget().isMinGW())
        lib.root_module.addCMacro("NOCRYPT", "1");
    lib.root_module.addCSourceFiles(.{
        .files = &.{
            "vendor/openssl-zig/ssl/bio_ssl.c",
            "vendor/openssl-zig/ssl/d1_lib.c",
            "vendor/openssl-zig/ssl/d1_msg.c",
            "vendor/openssl-zig/ssl/d1_srtp.c",
            "vendor/openssl-zig/ssl/methods.c",
            "vendor/openssl-zig/ssl/pqueue.c",
            "vendor/openssl-zig/ssl/priority_queue.c",
            // "ssl/quic/cc_newreno.c",
            // "ssl/quic/quic_ackm.c",
            // "ssl/quic/quic_cfq.c",
            // "ssl/quic/quic_channel.c",
            // "ssl/quic/quic_demux.c",
            // "ssl/quic/quic_fc.c",
            // "ssl/quic/quic_fifd.c",
            // "ssl/quic/quic_impl.c",
            // "ssl/quic/quic_method.c",
            // "ssl/quic/quic_reactor.c",
            // "ssl/quic/quic_record_rx.c",
            // "ssl/quic/quic_record_shared.c",
            // "ssl/quic/quic_record_tx.c",
            // "ssl/quic/quic_record_util.c",
            // "ssl/quic/quic_rstream.c",
            // "ssl/quic/quic_rx_depack.c",
            // "ssl/quic/quic_sf_list.c",
            // "ssl/quic/quic_sstream.c",
            // "ssl/quic/quic_statm.c",
            // "ssl/quic/quic_stream_map.c",
            // "ssl/quic/quic_thread_assist.c",
            // "ssl/quic/quic_tls.c",
            // "ssl/quic/quic_tserver.c",
            // "ssl/quic/quic_txp.c",
            // "ssl/quic/quic_txpim.c",
            // "ssl/quic/quic_wire.c",
            // "ssl/quic/quic_wire_pkt.c",
            // "ssl/quic/uint_set.c",
            "vendor/openssl-zig/ssl/record/methods/dtls_meth.c",
            // "ssl/record/methods/ktls_meth.c",
            "vendor/openssl-zig/ssl/record/methods/ssl3_cbc.c",
            "vendor/openssl-zig/ssl/record/methods/ssl3_meth.c",
            "vendor/openssl-zig/ssl/record/methods/tls13_meth.c",
            "vendor/openssl-zig/ssl/record/methods/tls1_meth.c",
            "vendor/openssl-zig/ssl/record/methods/tls_common.c",
            "vendor/openssl-zig/ssl/record/methods/tls_multib.c",
            "vendor/openssl-zig/ssl/record/methods/tls_pad.c",
            "vendor/openssl-zig/ssl/record/methods/tlsany_meth.c",
            "vendor/openssl-zig/ssl/record/rec_layer_d1.c",
            "vendor/openssl-zig/ssl/record/rec_layer_s3.c",
            "vendor/openssl-zig/ssl/s3_enc.c",
            "vendor/openssl-zig/ssl/s3_lib.c",
            "vendor/openssl-zig/ssl/s3_msg.c",
            "vendor/openssl-zig/ssl/ssl_asn1.c",
            "vendor/openssl-zig/ssl/ssl_cert.c",
            "vendor/openssl-zig/ssl/ssl_cert_comp.c",
            "vendor/openssl-zig/ssl/ssl_ciph.c",
            "vendor/openssl-zig/ssl/ssl_conf.c",
            "vendor/openssl-zig/ssl/ssl_err_legacy.c",
            "vendor/openssl-zig/ssl/ssl_init.c",
            "vendor/openssl-zig/ssl/ssl_lib.c",
            "vendor/openssl-zig/ssl/ssl_mcnf.c",
            "vendor/openssl-zig/ssl/ssl_rsa.c",
            // "ssl/ssl_rsa_legacy.c",
            "vendor/openssl-zig/ssl/ssl_sess.c",
            "vendor/openssl-zig/ssl/ssl_stat.c",
            "vendor/openssl-zig/ssl/ssl_txt.c",
            "vendor/openssl-zig/ssl/ssl_utst.c",
            "vendor/openssl-zig/ssl/statem/extensions.c",
            "vendor/openssl-zig/ssl/statem/extensions_clnt.c",
            "vendor/openssl-zig/ssl/statem/extensions_cust.c",
            "vendor/openssl-zig/ssl/statem/extensions_srvr.c",
            "vendor/openssl-zig/ssl/statem/statem.c",
            "vendor/openssl-zig/ssl/statem/statem_clnt.c",
            "vendor/openssl-zig/ssl/statem/statem_dtls.c",
            "vendor/openssl-zig/ssl/statem/statem_lib.c",
            "vendor/openssl-zig/ssl/statem/statem_srvr.c",
            "vendor/openssl-zig/ssl/t1_enc.c",
            "vendor/openssl-zig/ssl/t1_lib.c",
            "vendor/openssl-zig/ssl/t1_trce.c",
            "vendor/openssl-zig/ssl/tls13_enc.c",
            "vendor/openssl-zig/ssl/tls_depr.c",
            "vendor/openssl-zig/ssl/tls_srp.c",
        },
        .flags = cflags,
    });
    lib.linkLibC();
    return lib;
}

fn libprovider(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode) *std.Build.Step.Compile {
    const lib = b.addStaticLibrary(.{
        .name = "providers",
        .target = target,
        .optimize = optimize,
    });
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/include"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/providers/common/include"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/providers/fips/include"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/providers/implementations/include"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/include_gen"));
    lib.root_module.addIncludePath(b.path("vendor/openssl-zig/crypto"));
    lib.root_module.addCMacro("OPENSSL_NO_DEPRECATED", "");
    lib.root_module.addCMacro("OPENSSL_NO_ENGINE", "");
    lib.root_module.addCMacro("OPENSSL_NO_SRP", "");
    lib.root_module.addCMacro("OPENSSL_NO_UI_CONSOLE", "");
    lib.root_module.addCMacro("OPENSSL_NO_ASAN", "");
    lib.root_module.addCMacro("OPENSSL_NO_ASM", "");
    lib.root_module.addCMacro("OPENSSL_NO_KTLS", "");
    lib.root_module.addCMacro("OPENSSL_NO_QUIC", "");
    lib.root_module.addCMacro("OPENSSL_CPUID_OBJ", "");
    if (lib.rootModuleTarget().os.tag.isDarwin()) {
        // CommonCrypto
        lib.root_module.linkFramework("CoreServices", .{});
        lib.root_module.addCMacro("OPENSSL_SYS_MACOSX", "1");
        lib.root_module.addSystemIncludePath(.{ .cwd_relative = "/usr/include" });
    }
    if (lib.rootModuleTarget().isMinGW())
        lib.root_module.addCMacro("NOCRYPT", "1");
    lib.root_module.addCSourceFiles(.{
        .files = switch (lib.rootModuleTarget().cpu.arch) {
            .x86, .x86_64 => &.{
                "vendor/openssl-zig/providers/implementations/rands/seeding/rand_cpu_x86.c",
            },
            .aarch64 => &.{
                "vendor/openssl-zig/providers/implementations/rands/seeding/rand_cpu_arm64.c",
            },
            else => &.{},
        },
        .flags = cflags,
    });
    lib.root_module.addCSourceFiles(.{
        .files = &.{
            "vendor/openssl-zig/include_gen/der/der_sm2_gen.c",
            "vendor/openssl-zig/include_gen/der/der_digests_gen.c",
            "vendor/openssl-zig/include_gen/der/der_dsa_gen.c",
            "vendor/openssl-zig/include_gen/der/der_ec_gen.c",
            "vendor/openssl-zig/include_gen/der/der_ecx_gen.c",
            "vendor/openssl-zig/include_gen/der/der_rsa_gen.c",
            "vendor/openssl-zig/include_gen/der/der_wrap_gen.c",
            "vendor/openssl-zig/providers/baseprov.c",
            "vendor/openssl-zig/providers/common/bio_prov.c",
            "vendor/openssl-zig/providers/common/capabilities.c",
            "vendor/openssl-zig/providers/common/der/der_dsa_key.c",
            "vendor/openssl-zig/providers/common/der/der_dsa_sig.c",
            "vendor/openssl-zig/providers/common/der/der_ec_key.c",
            "vendor/openssl-zig/providers/common/der/der_ec_sig.c",
            "vendor/openssl-zig/providers/common/der/der_ecx_key.c",
            "vendor/openssl-zig/providers/common/der/der_rsa_key.c",
            "vendor/openssl-zig/providers/common/der/der_rsa_sig.c",
            "vendor/openssl-zig/providers/common/der/der_sm2_key.c",
            "vendor/openssl-zig/providers/common/der/der_sm2_sig.c",
            "vendor/openssl-zig/providers/common/digest_to_nid.c",
            "vendor/openssl-zig/providers/common/provider_ctx.c",
            "vendor/openssl-zig/providers/common/provider_err.c",
            "vendor/openssl-zig/providers/common/provider_seeding.c",
            "vendor/openssl-zig/providers/common/provider_util.c",
            "vendor/openssl-zig/providers/common/securitycheck.c",
            "vendor/openssl-zig/providers/common/securitycheck_default.c",
            // "providers/common/securitycheck_fips.c",
            "vendor/openssl-zig/providers/defltprov.c",
            // "providers/fips/fips_entry.c",
            // "providers/fips/fipsprov.c",
            // "providers/fips/self_test.c",
            // "providers/fips/self_test_kats.c",
            "vendor/openssl-zig/providers/implementations/asymciphers/rsa_enc.c",
            "vendor/openssl-zig/providers/implementations/asymciphers/sm2_enc.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_cbc_hmac_sha.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_cbc_hmac_sha1_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_cbc_hmac_sha256_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_ccm.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_ccm_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_gcm.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_gcm_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_gcm_siv.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_gcm_siv_polyval.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_ocb.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_ocb_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_siv.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_siv_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_wrp.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_xts.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_xts_fips.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aes_xts_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aria.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aria_ccm.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aria_ccm_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aria_gcm.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aria_gcm_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_aria_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_blowfish.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_blowfish_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_camellia.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_camellia_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_cast5.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_cast5_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_chacha20.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_chacha20_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_chacha20_poly1305_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_cts.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_des.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_des_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_desx.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_desx_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_idea.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_idea_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_null.c",
            // "providers/implementations/ciphers/cipher_rc2.c",
            // "providers/implementations/ciphers/cipher_rc2_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_rc4.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_rc4_hmac_md5.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_rc4_hmac_md5_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_rc4_hw.c",
            // "providers/implementations/ciphers/cipher_rc5.c",
            // "providers/implementations/ciphers/cipher_rc5_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_seed.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_seed_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_sm4.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_sm4_ccm.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_sm4_ccm_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_sm4_gcm.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_sm4_gcm_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_sm4_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_sm4_xts.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_sm4_xts_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_tdes.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_tdes_common.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_tdes_default.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_tdes_default_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_tdes_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_tdes_wrap.c",
            "vendor/openssl-zig/providers/implementations/ciphers/cipher_tdes_wrap_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/ciphercommon_block.c",
            "vendor/openssl-zig/providers/implementations/ciphers/ciphercommon_ccm.c",
            "vendor/openssl-zig/providers/implementations/ciphers/ciphercommon_ccm_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/ciphercommon_gcm.c",
            "vendor/openssl-zig/providers/implementations/ciphers/ciphercommon_gcm_hw.c",
            "vendor/openssl-zig/providers/implementations/ciphers/ciphercommon_hw.c",
            "vendor/openssl-zig/providers/implementations/digests/blake2_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/blake2b_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/blake2s_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/digestcommon.c",
            // "providers/implementations/digests/md2_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/md4_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/md5_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/md5_sha1_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/mdc2_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/null_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/ripemd_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/sha2_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/sha3_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/sm3_prov.c",
            "vendor/openssl-zig/providers/implementations/digests/wp_prov.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/decode_der2key.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/decode_epki2pki.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/decode_msblob2key.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/decode_pem2der.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/decode_pvk2key.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/decode_spki2typespki.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/encode_key2any.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/encode_key2blob.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/encode_key2ms.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/encode_key2text.c",
            "vendor/openssl-zig/providers/implementations/encode_decode/endecoder_common.c",
            "vendor/openssl-zig/providers/implementations/exchange/dh_exch.c",
            "vendor/openssl-zig/providers/implementations/exchange/ecdh_exch.c",
            "vendor/openssl-zig/providers/implementations/exchange/ecx_exch.c",
            "vendor/openssl-zig/providers/implementations/exchange/kdf_exch.c",
            "vendor/openssl-zig/providers/implementations/kdfs/argon2.c",
            "vendor/openssl-zig/providers/implementations/kdfs/hkdf.c",
            "vendor/openssl-zig/providers/implementations/kdfs/hmacdrbg_kdf.c",
            "vendor/openssl-zig/providers/implementations/kdfs/kbkdf.c",
            "vendor/openssl-zig/providers/implementations/kdfs/krb5kdf.c",
            "vendor/openssl-zig/providers/implementations/kdfs/pbkdf1.c",
            "vendor/openssl-zig/providers/implementations/kdfs/pbkdf2.c",
            "vendor/openssl-zig/providers/implementations/kdfs/pbkdf2_fips.c",
            "vendor/openssl-zig/providers/implementations/kdfs/pkcs12kdf.c",
            "vendor/openssl-zig/providers/implementations/kdfs/pvkkdf.c",
            "vendor/openssl-zig/providers/implementations/kdfs/scrypt.c",
            "vendor/openssl-zig/providers/implementations/kdfs/sshkdf.c",
            "vendor/openssl-zig/providers/implementations/kdfs/sskdf.c",
            "vendor/openssl-zig/providers/implementations/kdfs/tls1_prf.c",
            "vendor/openssl-zig/providers/implementations/kdfs/x942kdf.c",
            "vendor/openssl-zig/providers/implementations/kem/ec_kem.c",
            "vendor/openssl-zig/providers/implementations/kem/ecx_kem.c",
            "vendor/openssl-zig/providers/implementations/kem/kem_util.c",
            "vendor/openssl-zig/providers/implementations/kem/rsa_kem.c",
            "vendor/openssl-zig/providers/implementations/keymgmt/dh_kmgmt.c",
            "vendor/openssl-zig/providers/implementations/keymgmt/dsa_kmgmt.c",
            "vendor/openssl-zig/providers/implementations/keymgmt/ec_kmgmt.c",
            "vendor/openssl-zig/providers/implementations/keymgmt/ecx_kmgmt.c",
            "vendor/openssl-zig/providers/implementations/keymgmt/kdf_legacy_kmgmt.c",
            "vendor/openssl-zig/providers/implementations/keymgmt/mac_legacy_kmgmt.c",
            "vendor/openssl-zig/providers/implementations/keymgmt/rsa_kmgmt.c",
            // "providers/implementations/macs/blake2_mac_impl.c",
            "vendor/openssl-zig/providers/implementations/macs/blake2b_mac.c",
            "vendor/openssl-zig/providers/implementations/macs/blake2s_mac.c",
            "vendor/openssl-zig/providers/implementations/macs/cmac_prov.c",
            "vendor/openssl-zig/providers/implementations/macs/gmac_prov.c",
            "vendor/openssl-zig/providers/implementations/macs/hmac_prov.c",
            "vendor/openssl-zig/providers/implementations/macs/kmac_prov.c",
            "vendor/openssl-zig/providers/implementations/macs/poly1305_prov.c",
            "vendor/openssl-zig/providers/implementations/macs/siphash_prov.c",
            "vendor/openssl-zig/providers/implementations/rands/drbg.c",
            "vendor/openssl-zig/providers/implementations/rands/drbg_ctr.c",
            "vendor/openssl-zig/providers/implementations/rands/drbg_hash.c",
            "vendor/openssl-zig/providers/implementations/rands/drbg_hmac.c",
            "vendor/openssl-zig/providers/implementations/rands/seed_src.c",
            "vendor/openssl-zig/providers/implementations/rands/seeding/rand_tsc.c",
            if (lib.rootModuleTarget().os.tag == .windows)
                "vendor/openssl-zig/providers/implementations/rands/seeding/rand_win.c"
            else
                "vendor/openssl-zig/providers/implementations/rands/seeding/rand_unix.c",
            // "providers/implementations/rands/seeding/rand_vms.c",
            // "providers/implementations/rands/seeding/rand_vxworks.c",
            // "providers/implementations/rands/test_rng.c",
            "vendor/openssl-zig/providers/implementations/signature/dsa_sig.c",
            "vendor/openssl-zig/providers/implementations/signature/ecdsa_sig.c",
            "vendor/openssl-zig/providers/implementations/signature/eddsa_sig.c",
            "vendor/openssl-zig/providers/implementations/signature/mac_legacy_sig.c",
            "vendor/openssl-zig/providers/implementations/signature/rsa_sig.c",
            "vendor/openssl-zig/providers/implementations/signature/sm2_sig.c",
            "vendor/openssl-zig/providers/implementations/storemgmt/file_store.c",
            "vendor/openssl-zig/providers/implementations/storemgmt/file_store_any2obj.c",
            // "providers/implementations/storemgmt/winstore_store.c",
            "vendor/openssl-zig/providers/legacyprov.c",
            "vendor/openssl-zig/providers/nullprov.c",
            "vendor/openssl-zig/providers/prov_running.c",
        },
        .flags = cflags,
    });
    lib.linkLibC();
    return lib;
}

const cflags = &.{
    "-std=gnu89",
    "-Wno-unknown-warning-option",
    "-Wswitch-default",
    "-Wno-parentheses-equality",
    "-Wno-language-extension-token",
    "-Wno-extended-offsetof",
    "-Wconditional-uninitialized",
    "-Wincompatible-pointer-types-discards-qualifiers",
    "-Wmissing-variable-declarations",
    "-Wno-int-conversion",
};

const BuildInfo = struct {
    path: []const u8,
    fn filename(self: BuildInfo) []const u8 {
        var split = std.mem.splitSequence(u8, std.fs.path.basename(self.path), ".");
        return split.first();
    }
};
